### ISSUE TITLE
Flutter web support

### ISSUE THREAD

**Issue by NitrogenWC** [appcues/appcues-flutter-plugin#69]
Flutter supports not only mobile, so it would be great if you add flutter web also

**Comment by andretortolano** [comment]
Hey @NitrogenWC thanks for the feedback, at this moment the support for Flutter Web is not in our roadmap. 

Currently Appcues Web and Mobile are two different installations, you can learn more about it in our [installation docs](https://docs.appcues.com/en_US/dev-installing-appcues/appcues-installation-overview).
